const cron = require('node-cron');
const { query } = require('../services/db');
const { generatePulseRecap } = require('../services/groq');
const axios = require('axios');

// Run every Monday at 9:00 AM UTC
cron.schedule('0 9 * * 1', async () => {
  console.log('[Pulse Cron] Starting weekly recap generation...');

  try {
    // Get all active teams on plans that include Pulse (basic+)
    const teams = await query(
      `SELECT t.id, t.name, t.plan,
              i.access_token AS slack_token,
              i.metadata AS slack_meta
       FROM teams t
       LEFT JOIN integrations i ON i.team_id = t.id AND i.type = 'slack' AND i.status = 'connected'
       WHERE t.plan != 'free'`
    );

    for (const team of teams.rows) {
      try {
        // Get last 7 days of messages
        const messages = await query(
          `SELECT content, source, source_channel, author_name, sent_at
           FROM messages
           WHERE team_id = $1 AND sent_at >= NOW() - INTERVAL '7 days'
           ORDER BY sent_at DESC LIMIT 300`,
          [team.id]
        );

        if (messages.rows.length === 0) continue;

        const now = new Date();
        const weekStart = new Date(now);
        weekStart.setDate(now.getDate() - 7);
        const weekRange = `${weekStart.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – ${now.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`;

        const recap = await generatePulseRecap(messages.rows, weekRange);

        // Save to DB
        await query(
          `INSERT INTO pulse_recaps (team_id, week_start, week_end, content)
           VALUES ($1, $2, $3, $4)`,
          [team.id, weekStart, now, JSON.stringify(recap)]
        );

        // Post to Slack if connected
        if (team.slack_token) {
          const channel = team.slack_meta?.pulse_channel || '#general';
          const slackMsg = formatPulseForSlack(recap, weekRange);

          await axios.post('https://slack.com/api/chat.postMessage', {
            channel,
            blocks: slackMsg
          }, {
            headers: { Authorization: `Bearer ${team.slack_token}` }
          });
        }

        await query(
          `INSERT INTO activity (team_id, type, description)
           VALUES ($1, 'pulse_generated', 'Automated weekly Pulse recap generated')`,
          [team.id]
        );

        console.log(`[Pulse Cron] Generated recap for team ${team.name}`);
      } catch (err) {
        console.error(`[Pulse Cron] Failed for team ${team.id}:`, err.message);
      }
    }

    console.log('[Pulse Cron] Done.');
  } catch (err) {
    console.error('[Pulse Cron] Fatal error:', err);
  }
});

function formatPulseForSlack(recap, weekRange) {
  const blocks = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `🔴 Redstone Pulse — ${weekRange}` }
    },
    { type: 'divider' }
  ];

  if (recap.key_discussions?.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Key Discussions*\n${recap.key_discussions.map(d => `• ${d}`).join('\n')}`
      }
    });
  }

  if (recap.unresolved_questions?.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*⚠️ Unresolved Questions*\n${recap.unresolved_questions.map(q => `• ${q}`).join('\n')}`
      }
    });
  }

  if (recap.action_items?.length > 0) {
    const items = recap.action_items.map(a =>
      `• ${a.task}${a.owner ? ` _(${a.owner})_` : ''}`
    ).join('\n');
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Action Items*\n${items}` }
    });
  }

  blocks.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: '_Generated by Redstone · redstone.app_' }]
  });

  return blocks;
}

console.log('[Pulse Cron] Scheduled — runs every Monday at 9:00 AM UTC');
